### ISSUE TITLE
More helpful errors?

### ISSUE THREAD

**Issue by fatuhoku** [mozilla/node-convict#92] opened 2015-09-08 13:17 UTC
I've seen this kind of error really often.

The configuration file being loaded:

``` json
// config/default.json
{
  "parse": {
      "account": {
          "email": "Set up your Parse account's email in XYZ.config.",
          "password": "Set up your Parse account's password in XYZ.config."
      }
  }
}
```

The code loading it

``` js
    var conf = convict({
        parse: {
            account: {
                email: {
                    doc: "Parse account email address.",
                    format: "email",
                    env: "PARSE_EMAIL",
                },
                password: {
                    doc: "Parse account password.",
                    format: 'string',
                    env: "PARSE_PASSWORD"
                }
            }
        },
    }).loadFile('config/default.json').validate({strict:true});
```

The error trace:

``` js
Error: configuration param '0' not declared in the schema
        configuration param '1' not declared in the schema
        configuration param '2' not declared in the schema
        configuration param '3' not declared in the schema
        configuration param '4' not declared in the schema
        configuration param '5' not declared in the schema
        configuration param '6' not declared in the schema
```

These are opaque and completely unhelpful. What's going on?

**Comment by chiefy** [comment] 2015-12-19 15:12
:+1: just ran into this and have no idea what's going on?

**Comment by fkm** [comment] 2016-03-25 12:26
The strict validation seems to have some really strict guidelines on what a complete definition is.

Remove strict validation and you'll be fine.

**Comment by chiefy** [comment] 2016-03-25 12:58
@fkm I was getting errors like these w/out `strict:true`

**Comment by madarche** [comment] 2017-04-02 08:10
This problem arises when no `default` property is set for a field. We should better check schema validity on schema creation.

**Comment by madarche** [comment] 2017-04-02 08:12
Duplicate of  #88

**Closed by madarche** 2017-04-02 08:12 UTC
