### ISSUE TITLE
Convict + react-scripts build + CI=true throws error

### ISSUE THREAD

**Issue by deema089786** [mozilla/node-convict#385] opened 2021-04-28 14:40 UTC
When I try to build React app with `react-scripts build` (typescript) and env var CI=true I get this error
```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

./node_modules/yargs-parser/index.js
Critical dependency: the request of a dependency is an expression
```
When I remove all usage of Convict from my code or set CI=false - build goes as expected 

convict: 6.0.1
"@types/convict": "^6.0.1",
react-scripts: 4.0.3

NodeJS: 14.15.1

Is there any way to deal with that? (except setting CI to false)

**Comment by Dinodanio** [comment] 2021-08-12 07:42
+1 same here

**Comment by madarche** [comment] 2022-05-07 16:08
Duplicate of #400

**Closed by madarche** 2022-05-07 16:08 UTC
